import{i as a,S as c}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function f(n){const o="42127236-8bfdbbfbeed8a2dadaca720e8",r="https://pixabay.com/api/?key=",l=`&q=${n}&`,e=new URLSearchParams({image_type:"photo",orientation:"horisontal",safesearch:!0}),t=r+o+l+e;return fetch(t).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})}function u(n){return n.hits.map(r=>`<li class="gallery-item">
          <a href="${r.largeImageURL}"><img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" /></a>
          <div class="gallery-wrap">
          <p><b>Likes</b><br />${r.likes}</p>
          <p><b>Views</b><br />${r.views}</p>
          <p><b>Comments</b><br />${r.comments}</p>
          <p><b>Downloads</b><br />${r.downloads}</p>
          </div>
        </li>`).join("")}const s={formRef:document.querySelector(".form"),formInputRef:document.querySelector(".form-input"),galleryRef:document.querySelector(".gallery"),loaderRef:document.querySelector(".loader")},m={captionDelay:250,captionsData:"alt"};s.formRef.addEventListener("submit",n=>{s.loaderRef.classList.remove("hide-loader"),n.preventDefault(),s.formInputRef.value.trim()===""?(s.formRef.reset(),s.galleryRef.innerHTML="",s.loaderRef.classList.add("hide-loader")):f(s.formInputRef.value).then(o=>{s.formRef.reset(),o.hits.length===0&&a.error({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"white",backgroundColor:"red",position:"topRight",maxWidth:432}),s.galleryRef.innerHTML=u(o);const r=new c(".gallery a",m);r.on("show.simplelightbox"),r.refresh()}).catch(o=>a.error({message:o,position:"topRight",maxWidth:432})).finally(()=>{s.loaderRef.classList.add("hide-loader")})});
//# sourceMappingURL=commonHelpers.js.map
